eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-zuul
server:
  port: 8087
#分配两个服务器的路由
zuul:
  routes:
    api-1:
      path: /ribbon/**
      serviceId: service-ribbon
    api-2:
      path: /feign/**
      serviceId: service-feign