
eureka:
  client:
    healthcheck: # 开启健康检查（需要spring-boot-starter-actuator依赖）只应该在application.yml中设置。
      #如果设置在bootstrap.yml中将会导致一些不良的副作用，例如在Eureka中注册的应用名称是UNKNOWN等
      enabled: true
      instance:
        lease-expiration-duration-in-seconds: 10 # 续约更新时间间隔,当服务关闭超过这个时间时，eureka服务器会清除掉这个服务（默认30秒）
        lease-renewal-interval-in-seconds: 30 # 续约到期时间,用于定时向服务器发送心跳请求（默认90秒）

