eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          # git仓库的地址
          uri: https://github.com/forezp/SpringcloudConfig
          #配置文件所在的目录
          search-paths: /respo
      # 配置文件所在的峰值
      label: master
      profile: dev
server:
  port: 8088
